[paths_win]
; Absolute paths for your Windows environment
python_path = U:/voothi/20250825231214-spacy-env/Scripts/python.exe
kardenwort_workspace = U:/voothi/20241223170748-kardenwort
importer_workspace = U:/voothi/20250401192017-anki-csv-importer

[paths_nix]
; Absolute paths for your Linux/macOS environment
python_path = /path/to/your/venv/bin/python
kardenwort_workspace = /path/to/your/kardenwort/project
importer_workspace = /path/to/your/anki-csv-importer

[scripts]
# Names of the executable scripts
kardenwort_script = kardenwort.py
importer_script = anki-csv-importer.py

[directories]
# Relative directory paths inside the kardenwort_workspace
data_dir = data
input_dir = in
output_dir = out

[filenames]
# Template for generating the output filename
# Variables: {mode}, {suffix}, {language}
output_template = result.{mode}.{suffix}.{language}.tsv

# Language-specific data files
lemma_file_en = en-news-2023-1m-words.csv
override_file_en = lemma_override_en.tsv

lemma_file_de = deu-mixed-typical-2011-1m-words.csv
override_file_de = lemma_override_de.tsv
dictionary_de = german.dic

[anki_importer]
# Settings for the Anki CSV Importer script
note_type = Basic 20240218092126